name: Build and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      coverage-file:
        required: false
        type: string
        default: coverage.xml

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    env:
      PYTHON_VERSION: ${{ inputs.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pipx install hatch==1.7.0

      - name: Run Unit Tests
        run: hatch run test:unit

      - name: Generate test coverage
        run: hatch run test:coverage-report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ inputs.coverage-file }}
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Piotr1215/killercoda-cli

